package constant

const (
	PaymentByFrom = "NGUOIGUI"
	PaymentByTo   = "NGUOINHAN"

	ServiceExtraCodePayment = "PaymentBy"
	ServiceExtraCodeTip     = "TIP"
	ServiceExtraXmg         = "XMG"
	ServiceExtraPickShift   = "PickShift"
	ServiceExtraCODT0       = "CODT0"
	ServiceExtraBulky       = "BULKY"
	ServiceExtraCODST       = "CODST"
	ServiceExtraConn        = "CONN"
	ServiceExtraPartSign    = "partsign"
	ServiceExtraThermalBag  = "THERMALBAG"
	ServiceExtraGbh         = "GBH"
	ServiceExtraShipperNote = "ShipperNote"
	ServiceExtraGnG         = "GNG"
	ServiceExtraRoundTrip   = "ROUND-TRIP"
	ServiceExtraPrepaid     = "PREPAID"
	ServiceExtraBaoPhat     = "BAOPHAT"
	ServiceExtraPtt         = "PTT"
	ServiceExtraDk          = "DK"
	ServiceExtraGHTK1       = "GHTK_1"
	ServiceExtraGHTK7       = "GHTK_7"
	ServiceExtraGHTKXFAST   = "GHTK_XFAST"
	ServiceExtraGHTK2       = "GHTK_2"
	ServiceExtraGHTK3       = "GHTK_3"
	ServiceExtraGHTK4       = "GHTK_4"
	ServiceExtraGHTK5       = "GHTK_5"
	ServiceExtraGHTK6       = "GHTK_6"
)
