mode: dev

app_key: 88cFcAB40657e1AA1EBf852c4060E6d257a02EFf88cFcAB40657e1AA1EBf852c4060E6d257a02EFf

log:
  enable_file: false
  file: ./ship.log
  max_size: 500 #megabytes
  max_backups: 3
  max_age: 30 #days

server:
  name: check-price
  address: 3456
  prefix: api/v4/check-price

mysql:
  host: 10.24.22.234
  port: 3306
  user: shipping
  password: cC1usteR@citigo
  db_name: kvshipping_prelive
  ssl_mode: disable
  auto_migrate: false
  max_life_time: 300

redis:
  expire_duration: 600
  hosts: 10.24.22.236:6379
  username: ""
  password: ""
  db: 0

ext_service:
  ghtk:
    host: https://services.giaohangtietkiem.vn
    token: 88cFcAB40657e1AA1EBf852c4060E6d257a02EFf
  ahamove:
    host: https://api.ahamove.com
    key: ced8e6c1d3375d098aa3f4329a6ba983
  voucher:
    host: https://voucher-shipping-prelive.kvpos.com
  ai_eliminating:
    host: https://datadepartment.citigo.net
    username: kship
    password: kCRzpjT5pY
swagger:
  enabled: false

tracer:
  enabled: false
  jaeger:
    endpoint: http://localhost:14268/api/traces
    active: true
